echo $DATABRICKS_HOST
echo $DATABRICKS_TOKEN
echo $DATABRICKS_ORDGID
echo $DATABRICKS_CLUSTER_ID


echo "y
$(DATABRICKS_HOST)
$(DATABRICKS_TOKEN)
$(DATABRICKS_CLUSTER_ID)
$(DATABRICKS_ORDGID)
15001" | databricks-connect configure